language: ruby
rvm:
- 2.0.0-p481
branches:
  only:
  - master
install:
- travis_retry bundle install
before_script:
- psql -c 'create database "klauzet_test";' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: t9oJSe2Bn8rqOC4BUb1xHFA3ICYexLtn+inEZujBhmLw2GrJC2Uc4JXgF11INJjyLnb31fXG9RHg9emOlzVDajnYPmSMhkTynDd2mQxVa94W8x5KfFa+aKDS96mhhEP/COalmzcnx14SaiBwiJOeDgU6l357c4rirUXgyI6mA2UYThvL6NNOA7zcHI2RGgZn6QcI0R8aepI6GOK17B1QFbbNgtEJq5OPYGI/EIc9QGdbqIhGRlYOvvbNuowU4BuSwT9ld7gItGiIz4SMksJTw7NCWM1wUExZYkAXAvg33mSPCfcqHkIw1VOfs+d6Q0wk2SGXC6l6whzy82jNRpA+NSQhZfMZ/jHQKaKuMS3R8ALp15JdfSDS84UJigLwO34Jn5V2A8NaLV9t2lORzEnZwtvUuAFhzXOHkHxQ/MHnoxnf/SXAKZB1YoK9vAShYcD455y1ks9DbvB+SkgQSsOqGGnnL897h95lKSbprBDG6RDgm1zYPf7ER2926KGkNcteQtHoMX0M00Peia6MjuJ6r/qTI5cmEnwcjKCfTrroH4jChX75uJYlSekD1veoZE20Ij/lJlqKc27cxeOR4bnffBSMz73gRElUq5oaoib44gkRUQehtfK3Ck5MdIGM79Mm/Wm2UpWn7fdoOONB0jHYeZs0Jfnhoix9WWP68hXVF6g=
  app: klauzettest
  run:
  - rake db:migrate
  - restart
